# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:18:39+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

app = MCPProxy(
    description='Below is the documentation for the API calls. You can try them out right here. \n',
    title='Fun Generators API',
    version='1.5',
    servers=[
        {'url': 'https://api.fungenerators.com'},
        {'url': 'http://api.fungenerators.com'},
    ],
)


@app.delete(
    '/riddle',
    description=""" Create a random Riddle entry. """,
    tags=['riddle_crud'],
    security=[
        APIKeyHeader(name="X-Fungenerators-Api-Secret"),
    ],
)
def delete_riddle(id: str):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/riddle',
    description=""" Get a Riddle entry for a given id. Retrieves a riddle question and answer based on the id. """,
    tags=['riddle_crud'],
    security=[
        APIKeyHeader(name="X-Fungenerators-Api-Secret"),
    ],
)
def get_riddle(id: Optional[str] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/riddle',
    description=""" Create a random Riddle entry. Same as 'PUT' but can be used when some of the client libraries don't support 'PUT'. """,
    tags=['riddle_crud'],
    security=[
        APIKeyHeader(name="X-Fungenerators-Api-Secret"),
    ],
)
def post_riddle(question: str, category: str = ..., answer: str = ...):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/riddle',
    description=""" Create a random Riddle entry. """,
    tags=['riddle_crud'],
    security=[
        APIKeyHeader(name="X-Fungenerators-Api-Secret"),
    ],
)
def put_riddle(question: str, category: str = ..., answer: str = ...):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/riddle/random',
    description=""" Get a random riddle for a given category(optional) """,
    tags=['riddle_crud'],
    security=[
        APIKeyHeader(name="X-Fungenerators-Api-Secret"),
    ],
)
def get_riddle_random(category: Optional[str] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/riddle/search',
    description=""" Search for random riddle which has the text in the query, for a given category(optional). """,
    tags=['riddle_crud'],
    security=[
        APIKeyHeader(name="X-Fungenerators-Api-Secret"),
    ],
)
def get_riddle_search(query: Optional[str] = None, category: Optional[str] = None):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
